export { sleep } from 'k6';
export { SharedArray } from 'k6/data';
export { ApiService } from '../../services/ApiService.js';
export { htmlReport } from 'https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js';
export { ENDPOINTS } from './constants.js';
export { environment } from '../config/environment.js';
export { generateRandomString } from '../functions/generate-random.js';
export { generateRandomNumber } from '../functions/generate-random.js'
export { deleteSpiderverse } from '../functions/delete-spiderverse.js';
export { registerManySpiderverse } from '../functions/register-many-spiderverse.js'
export { loginSpiderverse } from '../functions/login-spiderverse.js'
export { Checks } from "../utils/checks.js"